MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.15                  # [osx and x86_64]
c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
# Workaround addressing https://github.com/conda-forge/vc-feedstock/issues/83
cxx_compiler_version:  # [win]
  - 19.40              # [win]
  