c_stdlib_version:          # [osx]
  - "13.3"                 # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "13.3"                 # [osx]
c_compiler:      # [win]
  - vs2022       # [win]
cxx_compiler:    # [win]
  - vs2022       # [win]
libboost_devel:
  - '1.86'
