c_stdlib_version:          # [osx and x86_64]
  - "13.3"                 # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "13.3"                 # [osx and x86_64]
c_compiler:      # [win]
  - vs2022       # [win]
cxx_compiler:    # [win]
  - vs2022       # [win]
libboost_devel:
  - '1.86'
