{% set name = "power-grid-model" %}
{% set version = "1.6.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/power-grid-model-{{ version }}.tar.gz
  sha256: b0929db65372d75842abd94070c09fcc51fb22cbc02923afbad16f6dcf1452ef

build:
  skip: true  # [py<37 or win32 or ppc64le or (python_impl == 'pypy')]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - eigen
    - boost-cpp
    - msgpack-cxx
    - nlohmann_json

  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - msgpack-python

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model.readthedocs.io/
  dev_url: https://github.com/PowerGridModel/power-grid-model

extra:
  recipe-maintainers:
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
