{% set name = "power-grid-model" %}
{% set version = "1.10.67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PowerGridModel/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dc3d36746ad63e44f8695e09911783c09ce4a23295b8386e4e2f39956a9bc673

build:
  skip: true  # [py<311 or win32 or ppc64le or (python_impl == 'pypy')]
  number: 0
  env:
    {% if target_platform == "osx-arm64" or target_platform == "osx-64" %}
    MACOSX_DEPLOYMENT_TARGET: "13.3"
    {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - eigen
    - libboost-devel
    - msgpack-cxx
    - nlohmann_json
    - ninja
    - cmake

  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - msgpack-python

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model.readthedocs.io/
  dev_url: https://github.com/PowerGridModel/power-grid-model

extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
