{% set name = "power-grid-model" %}
{% set version = "1.10.59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # url: https://github.com/PowerGridModel/{{ name }}/archive/v{{ version }}.tar.gz
  url: https://github.com/PowerGridModel/power-grid-model/archive/separate-math-solver.tar.gz
  sha256: ddd54a14006f51eadcec9718748947daa4decf7321fa0a7f33bae57d9372542e

build:
  skip: true  # [py<311 or win32 or ppc64le or (python_impl == 'pypy')]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - eigen
    - libboost-headers
    - msgpack-cxx
    - nlohmann_json
    - ninja
    - cmake

  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - msgpack-python

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model.readthedocs.io/
  dev_url: https://github.com/PowerGridModel/power-grid-model

extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
