{% set name = "power-grid-model" %}
{% set version = "1.10.49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f4b772a80ed3b602349af85f8e4812275278520f6f805298aa115e2496124763

build:
  skip: true  # [py<311 or win32 or ppc64le or (python_impl == 'pypy')]
  script: {{ PYTHON }} -m pip install . -vv --global-option="build_ext" --global-option="-j1"
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - eigen
    - libboost-headers
    - msgpack-cxx
    - nlohmann_json

  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - msgpack-python

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model.readthedocs.io/
  dev_url: https://github.com/PowerGridModel/power-grid-model

extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
