{% set name = "power-grid-model" %}
{% set version = "1.9.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: abc5434d37d725d2264aa1331f763ba3fc32b5606908084c223a008418e8d8ba

build:
  skip: true  # [py<310 or win32 or ppc64le or (python_impl == 'pypy')]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - eigen
    - libboost-headers
    - msgpack-cxx
    - nlohmann_json

  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov
    - msgpack-python

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model.readthedocs.io/
  dev_url: https://github.com/PowerGridModel/power-grid-model

extra:
  recipe-maintainers:
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
