schema_version: 1

context:
  feedstock_name: power-grid-model
  version: "1.13.99"

recipe:
  name: power-grid-model
  version: ${{ version }}

source:
  url: https://github.com/PowerGridModel/${{ feedstock_name }}/archive/v${{ version }}.tar.gz
  sha256: f5ec410222ae8b5259710d588d5a0e278470bc4131a236fb1101298aaf291277

build:
  number: 1
  skip: (python_impl == 'pypy')


# multi stage build to build the C++ library and the Python bindings separately
outputs:
  
  # Build the C++ library for all platforms
  - package:
      name: "libpower-grid-model"
      version: ${{ version }}

    build:
      script:
        file: ${{ "build_libpower-grid-model.bat" if win else "build_libpower-grid-model.sh" }}
      variant:
        # libpower-grid-model is a pure C++ library
        # so the package is not Python-versioned.
        ignore_keys:
          - python

    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - ninja
        - cmake
        - eigen
        - libboost-devel
        - msgpack-cxx
        - nlohmann_json

      # empty host requirements to avoid pinning the header-only dependencies in runtime
      host:

      run_exports:
        # pin stable ABI on major version
        - ${{ pin_subpackage('libpower-grid-model', upper_bound='x') }}

    tests:
      - files:
          source:
            - tests/package_tests
        requirements:
          run:
            - cmake
            - ninja
            - ${{ compiler('cxx') }}
            - ${{ stdlib("c") }}

        # TODO add test
        script:
          - if: unix
            then:
              - cd tests/package_tests
              - mkdir build
              - cmake ${CMAKE_ARGS} -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release
              - cmake --build build
              - ./build/power_grid_model_package_test
          - if: win
            then:
              - cd tests/package_tests

  # Build the Python bindings for all platforms
  - package:
      name: "power-grid-model"
      version: ${{ version }}

    build:
      noarch: python
      skip: not (linux and x86_64)
      script:
        file: ${{ "build_power-grid-model.bat" if win else "build_power-grid-model.sh" }}

    requirements:
      
      # not build requirements
      build:

      host:
        - python ${{ python_min }}.*
        - scikit-build-core
        - pip
      run:
        - python >= ${{ python_min }}
        - ${{ pin_subpackage('libpower-grid-model', upper_bound='x.x.x') }}
        - numpy >=2.0.0

    tests:
      - python:
          imports:
            - power_grid_model
          pip_check: true
      - files:
          source:
            - tests/unit
            - tests/data
            - pyproject.toml
        requirements:
          run:
            - pip
            - pytest
            - pytest-cov
            - msgpack-python
            - colorama
        script:
          - pytest

about:
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://lfenergy.org/projects/power-grid-model/
  repository: https://github.com/PowerGridModel/power-grid-model
  documentation: https://power-grid-model.readthedocs.io/

extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
