schema_version: 1

context:
  name: power-grid-model
  version: "1.13.91"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/PowerGridModel/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 6642e1efd25f872f5af10b99766e74c17b3656a452e616733aefe984ea012dd9

build:
  number: 0
  skip: match(python, "<3.12") or match(python, ">3.12") or win32 or ppc64le or (python_impl == 'pypy')
  python:
    version_independent: true

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - eigen
    - libboost-devel
    - msgpack-cxx
    - nlohmann_json
    - ninja
    - cmake
  host:
    - python
    - scikit-build-core
    - pip
  run:
    - python
    - numpy >=2.0.0

tests:
  - python:
      imports:
        - power_grid_model
      pip_check: true
  - files:
      source:
        - tests
        - pyproject.toml
    requirements:
      run:
        - pip
        - pytest
        - pytest-cov
        - msgpack-python
        - colorama
    script:
      - pytest

about:
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://lfenergy.org/projects/power-grid-model/
  repository: https://github.com/PowerGridModel/power-grid-model
  documentation: https://power-grid-model.readthedocs.io/

extra:
  recipe-maintainers:
    - figueroa1395
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
