github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true

build_platform:
  osx_arm64: osx_64

provider:
  linux_aarch64: default

test: native_and_emulated
