bot:
  automerge: true
build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_arm64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: default
  linux_aarch64: default
  linux_ppc64le: None
  osx_64: default
  osx_arm64: default
  win_64: default
  win_32: None
test: native
conda_install_tool: pixi
conda_build_tool: rattler-build
